/*

 LEVEL1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\TestTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level1MapWidth 40
#define Level1MapHeight 18
#define Level1MapBank 0

extern unsigned char Level1Map[];

/* End of LEVEL1MAP.H */
