/*

 MAPLEVEL1_1EDGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 18
   Tile set      : TestTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel1_1edgeWidth 8
#define MapLevel1_1edgeHeight 18
#define MapLevel1_1edgeBank 0

extern unsigned char MapLevel1_1edge[];

/* End of MAPLEVEL1_1EDGE.H */
