/*

 MAPLEVEL2_2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : MotherboardTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel2_2Width 40
#define MapLevel2_2Height 18
#define MapLevel2_2Bank 0

extern unsigned char MapLevel2_2[];

/* End of MAPLEVEL2_2.H */
