/*

 MAPLEVEL4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\MotherboardTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel4Width 40
#define MapLevel4Height 18
#define MapLevel4Bank 0

extern unsigned char MapLevel4[];

/* End of MAPLEVEL4.H */
