/*

 MAPLEVEL5_20X18.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\MotherboardTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel5_20x18Width 20
#define MapLevel5_20x18Height 18
#define MapLevel5_20x18Bank 0

extern unsigned char MapLevel5_20x18[];

/* End of MAPLEVEL5_20X18.H */
