/*

 MAPLEVEL3_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\MotherboardTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel3_1Width 40
#define MapLevel3_1Height 18
#define MapLevel3_1Bank 0

extern unsigned char MapLevel3_1[];

/* End of MAPLEVEL3_1.H */
