/*

 MAPLEVEL6_32X18.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\TestTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLevel6_32x18Width 32
#define MapLevel6_32x18Height 18
#define MapLevel6_32x18Bank 0

extern unsigned char MapLevel6_32x18[];

/* End of MAPLEVEL6_32X18.H */
