/*

 TESTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\Dokumenty\Škola\Spongia2020\tilesets\TestTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestMapWidth 20
#define TestMapHeight 18
#define TestMapBank 0

extern unsigned char TestMap[];

/* End of TESTMAP.H */
